# Copyright (c) 2025 Hubble Network, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: buckleypaul
      url-base: https://github.com/buckleypaul

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0
      import: true
      west-commands: scripts/west-commands.yml
    - name: riglink
      remote: buckleypaul
      revision: main
      path: modules/lib/riglink
    - name: jcon
      remote: buckleypaul
      revision: main
      path: modules/lib/jcon

  self:
    path: modules/lib/hubblenetwork-sdk
