/*
 * Copyright (c) 2026 Hubble Network, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TEST_VECTORS_COUNTER_H
#define TEST_VECTORS_COUNTER_H

#include "test_vectors.h"

/* Counter-mode test vectors (pool_size=32) generated by ble-adv.py */
extern const struct ble_adv_test_vector counter_test_vectors[];
extern const size_t counter_test_vectors_count;

#endif /* TEST_VECTORS_COUNTER_H */
