name: Build TI Samples

on:
  pull_request:
    branches: ["**"]
    paths:
      - "include/**"
      - "src/**"
      - "samples/freertos/ti/**"
      - ".github/workflows/build-samples-ti.yaml"

  workflow_dispatch: {}

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build TI Samples
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/hubblenetwork/ti-ci-docker:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Build all TI samples
        run: python3 tools/ci/ti_build.py samples/freertos/ti
